# Generated by Django 5.0.6 on 2024-05-18 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pelanggaran',
            table='pelanggaran',
        ),
    ]
