# Generated by Django 5.0.6 on 2024-05-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaran', '0002_alter_pelanggaran_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pelanggarankategori',
            table='pelanggaran_kategori',
        ),
    ]
