# Generated by Django 5.0.6 on 2024-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaran', '0003_alter_pelanggarankategori_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggaran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
