# Generated by Django 5.0.6 on 2024-05-18 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='Tingkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.sekolah')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.jurusan')),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.sekolah')),
                ('tingkat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.tingkat')),
            ],
        ),
    ]
