# Generated by Django 5.0.6 on 2024-05-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_siswa_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='token_nobox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
