# Generated by Django 5.0.6 on 2024-05-18 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_superadmin_token_nobox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orangtua',
            name='siswa',
        ),
        migrations.AddField(
            model_name='siswa',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='orangtua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.orangtua'),
        ),
        migrations.AddField(
            model_name='staffsekolah',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffsekolah',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
