# Generated by Django 5.0.6 on 2024-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_orangtua_siswa_siswa_catatan_siswa_orangtua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsekolah',
            name='account_id_nobox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
