# Generated by Django 5.0.6 on 2024-05-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_adminsekolah_account_id_nobox'),
    ]

    operations = [
        migrations.AddField(
            model_name='orangtua',
            name='no_telp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
