# Generated by Django 5.0.6 on 2024-05-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orangtua_no_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsekolah',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
